[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "fastapi-inference-service"
version = "0.1.0"
description = "Production-ready FastAPI ML inference microservice with async jobs and monitoring"
authors = [
    {name = "Mohamed Alcafory", email = "mohamed.alcafory.456@gmail.com"}
]
requires-python = ">=3.11"
dependencies = [
    # FastAPI and ASGI
    "fastapi>=0.104.0",
    "uvicorn[standard]>=0.24.0",
    "gunicorn>=21.2.0",
    
    # ML and Data
    "scikit-learn>=1.3.0",
    "numpy>=1.24.0",
    "pandas>=2.0.0",
    "onnxruntime>=1.16.0",
    "onnx>=1.15.0",
    
    # Async Tasks
    "celery>=5.3.0",
    "redis>=5.0.0",
    
    # Monitoring and Metrics
    "prometheus-client>=0.19.0",
    "structlog>=23.2.0",
    
    # Utilities
    "pydantic>=2.5.0",
    "python-multipart>=0.0.6",
    "python-decouple>=3.8",
    "httpx>=0.25.0",
    "tenacity>=8.2.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.4.0",
    "pytest-asyncio>=0.21.0",
    "pytest-cov>=4.1.0",
    "pytest-mock>=3.12.0",
    "httpx>=0.25.0",
    "factory-boy>=3.3.0",
    "ruff>=0.1.0",
    "black>=23.0.0",
    "mypy>=1.5.0",
    "pre-commit>=3.4.0",
    "types-redis>=4.6.0",
]

load-test = [
    "locust>=2.17.0",
]

[tool.ruff]
target-version = "py311"
line-length = 88
select = ["E", "F", "I", "N", "UP", "S", "B", "A", "C4", "T20"]
ignore = ["E501", "S101", "N818"]

[tool.ruff.per-file-ignores]
"*/tests/*" = ["S101", "S106"]
"scripts/*" = ["T201"]

[tool.black]
line-length = 88
target-version = ['py311']

[tool.mypy]
python_version = "3.11"
strict = true
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true

[[tool.mypy.overrides]]
module = ["sklearn.*", "onnxruntime.*", "celery.*"]
ignore_missing_imports = true

[tool.pytest.ini_options]
asyncio_mode = "auto"
testpaths = ["tests"]
python_files = ["tests.py", "test_*.py", "*_tests.py"]
addopts = "--cov=app --cov-report=term-missing --cov-report=html"

[tool.coverage.run]
source = ["app"]
omit = [
    "*/tests/*",
    "*/venv/*",
    "*/__pycache__/*"
]